# Generated by Django 5.2 on 2026-03-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
