# Generated by Django 5.2 on 2026-03-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHome', '0002_alter_produto_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('motivo', models.TextField(max_length=100)),
                ('mensagem', models.TextField(max_length=300)),
            ],
        ),
    ]
