# Generated by Django 5.2 on 2026-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHome', '0003_suporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
