# Generated by Django 5.2.12 on 2026-03-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechHome', '0005_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=100),
        ),
    ]
